

install.packages("lubridate")
##load packages
library(plyr)
library(lubridate)
library(zoo)

#read the data
data <- read.csv("C:/Users/Tom McKeon/Desktop/UPenn/al.csv", header = TRUE)



##Make sure date is a date
data$date <- as.Date(data$date)

## I took monthly means first, there might be a more elegant solution
output <- aggregate(data$x, list(format(data$date, "%Y-%m"), data$plant), mean)
colnames(output) <- c('monthYear', 'plant', 'monthlyValue')
print(output)  ## Check

## I subsetted out each treatment plant to take each of their rolling averages individually... again there might be a more elegant solution
Queen_Lane <-subset(output, plant == "Queen Lane" , select = c("monthYear", "plant", "monthlyValue"), all = TRUE)
Baxter <-subset(output, plant == "Baxter" , select = c("monthYear", "plant", "monthlyValue"), all = TRUE)
Belmont <-subset(output, plant == "Belmont" , select = c("monthYear", "plant", "monthlyValue"), all = TRUE)
Mix <-subset(output, plant == "Baxter/Queen Lane Mix" , select = c("monthYear", "plant", "monthlyValue"), all = TRUE)



##rollapply seems like a good approach. The width takes four months. You can change this number to take rolling averages by different time periods
queenlane <- rollapply(Queen_Lane$monthlyValue, width = 4, FUN = mean)
baxter <- rollapply(Baxter$monthlyValue, width = 4, FUN = mean)
belmont <- rollapply(Belmont$monthlyValue, width = 4, FUN = mean)
mix <- rollapply(Mix$monthlyValue, width = 4, FUN = mean)

## The outputs weren't dataframes, so I converted back to one.
Queen_Lane_roll <- as.data.frame(queenlane)
Baxter_roll <- as.data.frame(baxter)
Belmont_roll <- as.data.frame(belmont)
Mix_roll <- as.data.frame(mix)

## Bring them back together
together <- cbind(Baxter_roll,Queen_Lane_roll,Belmont_roll,Mix_roll)



## Write out a csv file. It doesn't include a date column. but the order should be jan-april 2013, feb - may 2013, march - june 2013, etc
write.csv (together,
           file = "C:/Users/Tom McKeon/Desktop/UPenn/rollingaverage_andrea.csv",
           row.names = FALSE)

### I manually checked Baxter for jan 2013 through April 2013. 
### Happy to see the number matched the first entry of the csv file generated by R




